# Generated by Django 3.2.7 on 2021-09-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebay_item_number', models.CharField(max_length=255)),
                ('gocollect_link', models.URLField()),
                ('max_percent_of_price', models.IntegerField()),
                ('min_percent_of_price', models.IntegerField(default=85, null=True)),
                ('lowest_grade', models.CharField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5'), ('7.0', '7.0'), ('7.5', '7.5'), ('8.0', '8.0'), ('8.5', '8.5'), ('9.0', '9.0'), ('9.2', '9.2'), ('9.4', '9.4'), ('9.6', '9.6'), ('9.8', '9.8')], default='0', max_length=255)),
                ('highest_grade', models.CharField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5'), ('6.0', '6.0'), ('6.5', '6.5'), ('7.0', '7.0'), ('7.5', '7.5'), ('8.0', '8.0'), ('8.5', '8.5'), ('9.0', '9.0'), ('9.2', '9.2'), ('9.4', '9.4'), ('9.6', '9.6'), ('9.8', '9.8')], default='10', max_length=255)),
                ('negative_words', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
